### ISSUE TITLE
Incorrect frequency at exactly 32 kHz

### ISSUE THREAD

**Issue by chrishakim** [ivanseidel/DueTimer#36]
When I use setFrequency(32000), getFrequency() returns 31250, whereas if I do setFrequency(31999) or setFrequency(32001), getFrequency() returns 31987.81 and 32012.2 respectively. In the last two examples, the error is better than 0.1%. In the first example, it is -2.34375%. This cannot be a hardware limitation.

**Comment by ivanseidel** [comment]
Fixed in 1.4.6
