### ISSUE TITLE
Choose how many timers are instantiated isn't possible

### ISSUE THREAD

**Issue by q2dg** [ivanseidel/DueTimer#39]
I mean...do you think is good idea to instantiate all 9 timers automatically as a result of using this library? Maybe it would be more optimal to let the developer instantiate the timers he wants...

**Comment by ivanseidel** [comment]
Hi @q2dg , I followed the general pattern (usually, all are instantiated), I think they made in such way to facilitate the life of newbies. Sure it would be generally more "efficient" to not instantiate, but a few bytes on memory won't hurt anyone...

In any case, if you think it's a must, change the code to allow a definition like "INSTANTIATE_TIMERS=false" and make some preprocessing directives to skip that.

Thanks
