### ISSUE TITLE
Improvement of examples

### ISSUE THREAD

**Issue by q2dg** [ivanseidel/DueTimer#40]
The examples I think could be improved to include more than basic timer interrupt on a periodic basis, such as measurement of frequency or period, arbitrary waveform generation or quadrature decoding.
Anyway, thanks a lot for your job.

**Comment by ivanseidel** [comment]
Hi @q2dg , fell free to create some cool examples! This is open-source, we need help =)

**Comment by ivanseidel** [comment]
closing, but fell free to create pull requests
