### ISSUE TITLE
Read timer values

### ISSUE THREAD

**Issue by TheRealXav** [ivanseidel/DueTimer#46]
Hi, I don't qui understand how to use your library. What i want to do is start a timer, wait for a certain amount of time, and then read the value in this timer counter. I don't know if I make any sense, but is this feasible with your library as it is ?

Thanks for your time and your work, best regards
TheRealXav

**Comment by ivanseidel** [comment]
If you want to read only once:

```c++
void onceCalledFunction(){
  // Disables the timer after entering here
  Timer1.stop();

  // Execute whatever you want...
  // ...
}
void setup(){
  Timer1.setPeriod(1000). attachInterrupt(onceCalledFunction);
}

void loop(){
}
```
