### ISSUE TITLE
This library doesn't work

### ISSUE THREAD

**Issue by cyrilfr** [ivanseidel/DueTimer#49]
This library cannot be installed:
Invalid library found in /root/Arduino/libraries/DueTimer: Missing 'core-dependencies' from library

**Comment by Daniel-dk** [comment]
did you follow the installation instructions on : https://github.com/ivanseidel/DueTimer ?
and do you have "Arduino SAM Boards"  installed as a board in the Arduino IDE ( via boards manager ? ) 
Tools -> Board -> Boards Manager -> Arduino SAM boards

**Comment by cyrilfr** [comment]
No, I'm working with Arduino Due.

**Comment by Daniel-dk** [comment]
Arduino SAM Boards is the installation package that contains Arduino Due ( cortex M3 ) core dependancies

**Comment by cyrilfr** [comment]
I'm using a patched (bossac) version of Arduino IDE 1.5.4 compatible with the SAM3x of the UDOO Quad board. I must select "Arduino Due (Native Port)" in the "Board" menu. I don't have a SAM Boards entry.
