### ISSUE TITLE
PWM , hardware generating

### ISSUE THREAD

**Issue by abd-alaz** [ivanseidel/DueTimer#63]
Hi There
how to use the library to generate PWM (hardware) signal, something similar to the Mega2560 library please

http://playground.arduino.cc/Code/Timer1

regards

**Comment by ivanseidel** [comment]
Hi @abd-alaz, have you tried using `analogWrite(..)`? It generates PWM with a default clock frequency. You can also tweek the frequency and other things with a few hacks...
